### ISSUE TITLE
Milestone for the next version

### ISSUE THREAD

**Issue by sakanjo** [ikun-svelte/ikun-ui#233]
### Suggested solution

I was wondering if we can create a milestone in order to determine what should be added, updated to get this package published as stable.

**Comment by baiwusanyu-c** [comment]
`ikun-ui` is still in its infancy, and there are some short-term plans in #93 . When all the items in it are completed, version 0.0.9 will be released. It will be a usable version with relatively simple content.

**Comment by baiwusanyu-c** [comment]
Currently ikun-ui focuses on the improvement of some basic components, because many complex components (such as tables, multi-select boxes, forms, etc.) require the support of basic components. The community is currently very small. In addition to ikun-ui, I have to maintain other projects. The progress may be relatively slow. If you are interested in joining, I will invite you.

**Comment by sakanjo** [comment]
@baiwusanyu-c I will start working on completing some of #93 tasks.

I appreciate your invitation and i will jump right in.
